//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JqueryDatatable
{
    using System;
    using System.Collections.Generic;
    
    public partial class SampleCustomer
    {
        public string CustomerID { get; set; }
        public string PackageName { get; set; }
        public string Reporter { get; set; }
        public string Load { get; set; }
        public string Location { get; set; }
        public string Dep { get; set; }
    }
}
